#ifndef UE4SS_SDK_BPAntiTankExplosiveStickyBombDamageType_HPP
#define UE4SS_SDK_BPAntiTankExplosiveStickyBombDamageType_HPP

class UBPAntiTankExplosiveStickyBombDamageType_C : public USimDamageType
{
};

#endif
