#ifndef UE4SS_SDK_BPBattleTankCMachineGunnerComponent_HPP
#define UE4SS_SDK_BPBattleTankCMachineGunnerComponent_HPP

class UBPBattleTankCMachineGunnerComponent_C : public UBPColVehicleMachineGunnerComponent_C
{
};

#endif
