#ifndef UE4SS_SDK_BPBattleTankWMachineGunnerComponent_HPP
#define UE4SS_SDK_BPBattleTankWMachineGunnerComponent_HPP

class UBPBattleTankWMachineGunnerComponent_C : public UBPWarVehicleMachineGunnerComponent_C
{
};

#endif
