#ifndef UE4SS_SDK_BPEmplacementMortarMountComponent_HPP
#define UE4SS_SDK_BPEmplacementMortarMountComponent_HPP

class UBPEmplacementMortarMountComponent_C : public UEmplacementMortarMountComponent
{
};

#endif
