#ifndef UE4SS_SDK_BPHalfTrackOffensiveGunnerComponent_HPP
#define UE4SS_SDK_BPHalfTrackOffensiveGunnerComponent_HPP

class UBPHalfTrackOffensiveGunnerComponent_C : public UTankGunnerMountComponent
{
};

#endif
