#ifndef UE4SS_SDK_BPLightTank2InfantryC_Turret_L_GunnerComponent_HPP
#define UE4SS_SDK_BPLightTank2InfantryC_Turret_L_GunnerComponent_HPP

class UBPLightTank2InfantryC_Turret_L_GunnerComponent_C : public UBPColVehicleMachineGunnerComponent_C
{
};

#endif
