#ifndef UE4SS_SDK_BPMediumTank2IndirectWRackRPGGunner_HPP
#define UE4SS_SDK_BPMediumTank2IndirectWRackRPGGunner_HPP

class UBPMediumTank2IndirectWRackRPGGunner_C : public UProjectileGunnerMountComponent
{
};

#endif
