#ifndef UE4SS_SDK_BPMediumTank2CMachineGunnerComponent_HPP
#define UE4SS_SDK_BPMediumTank2CMachineGunnerComponent_HPP

class UBPMediumTank2CMachineGunnerComponent_C : public UBPColVehicleMachineGunnerComponent_C
{
};

#endif
