#ifndef UE4SS_SDK_BPMediumTank2MultiWMachineGunnerComponent_HPP
#define UE4SS_SDK_BPMediumTank2MultiWMachineGunnerComponent_HPP

class UBPMediumTank2MultiWMachineGunnerComponent_C : public UBPWarVehicleMachineGunnerComponent_C
{
};

#endif
