#ifndef UE4SS_SDK_BPMediumTankTopTurretGunnerMountComponent_HPP
#define UE4SS_SDK_BPMediumTankTopTurretGunnerMountComponent_HPP

class UBPMediumTankTopTurretGunnerMountComponent_C : public UTankGunnerMountComponent
{
};

#endif
