#ifndef UE4SS_SDK_BPMediumTankOffensiveCGunnerMountComponent_HPP
#define UE4SS_SDK_BPMediumTankOffensiveCGunnerMountComponent_HPP

class UBPMediumTankOffensiveCGunnerMountComponent_C : public UTankGunnerMountComponent
{
};

#endif
