#ifndef UE4SS_SDK_BPMotorcycleOffensiveGunnerComponent_HPP
#define UE4SS_SDK_BPMotorcycleOffensiveGunnerComponent_HPP

class UBPMotorcycleOffensiveGunnerComponent_C : public UBPTruckOffensiveGunnerComponent_C
{
};

#endif
