#ifndef UE4SS_SDK_BPRelicLightTankGunnerMountComponent_HPP
#define UE4SS_SDK_BPRelicLightTankGunnerMountComponent_HPP

class UBPRelicLightTankGunnerMountComponent_C : public UTankGunnerMountComponent
{
};

#endif
