#ifndef UE4SS_SDK_BPRelicMediumTankGunnerLMountComponent_HPP
#define UE4SS_SDK_BPRelicMediumTankGunnerLMountComponent_HPP

class UBPRelicMediumTankGunnerLMountComponent_C : public UTankGunnerMountComponent
{
};

#endif
