#ifndef UE4SS_SDK_BPRelicMediumTankGunnerRMountComponent_HPP
#define UE4SS_SDK_BPRelicMediumTankGunnerRMountComponent_HPP

class UBPRelicMediumTankGunnerRMountComponent_C : public UTankGunnerMountComponent
{
};

#endif
