#ifndef UE4SS_SDK_BPRelicAPCMachineGunnerComponentLeft_HPP
#define UE4SS_SDK_BPRelicAPCMachineGunnerComponentLeft_HPP

class UBPRelicAPCMachineGunnerComponentLeft_C : public UHitScanMountComponent
{
};

#endif
