#ifndef UE4SS_SDK_BPRelicBase3_HPP
#define UE4SS_SDK_BPRelicBase3_HPP

class ABPRelicBase3_C : public ABPRelicBase_C
{
    class USpawnPointComponent* SpawnPoint7;
    class USpawnPointComponent* SpawnPoint6;
    class USpawnPointComponent* SpawnPoint5;
    class USpawnPointComponent* SpawnPoint4;
    class USpawnPointComponent* SpawnPoint3;
    class USpawnPointComponent* SpawnPoint;
    class UStaticMeshComponent* StaticMesh1;
    class UStaticMeshComponent* StaticMesh3;
    class UStaticMeshComponent* StaticMesh2;
    class UBoxComponent* Box;
    class UMultiplexedStaticMeshComponent* MultiplexedGun;
    class UMultiplexedStaticMeshComponent* MultiplexedRoof;
    class UStaticMeshComponent* StaticMesh41;
    class UStaticMeshComponent* StaticMesh40;
    class UDecalComponent* Decal9;
    class UDecalComponent* Decal8;
    class UDecalComponent* Decal7;
    class UDecalComponent* Decal6;
    class UParticleSystemComponent* ParticleSystem4;
    class UDecalComponent* Decal5;
    class UParticleSystemComponent* ParticleSystem3;
    class UDecalComponent* Decal4;
    class UParticleSystemComponent* ParticleSystem2;
    class UParticleSystemComponent* ParticleSystem1;
    class UParticleSystemComponent* ParticleSystem;
    class UPointLightComponent* PointLight3;
    class UStaticMeshComponent* StaticMesh39;
    class UPointLightComponent* PointLight2;
    class UStaticMeshComponent* StaticMesh38;
    class UPointLightComponent* PointLight1;
    class UStaticMeshComponent* StaticMesh37;
    class UPointLightComponent* PointLight;
    class UStaticMeshComponent* StaticMesh36;
    class UChildActorComponent* ChildActor1;
    class USpotLightComponent* SpotLight1;
    class USpotLightComponent* SpotLight;
    class UStaticMeshComponent* StaticMesh31;
    class UChildActorComponent* ChildActor;
    class UStaticMeshComponent* Rope01;
    class UStaticMeshComponent* StaticMesh30;
    class UStaticMeshComponent* StaticMesh29;
    class UChildActorComponent* Crates;
    class UStaticMeshComponent* StaticMesh28;
    class UStaticMeshComponent* StaticMesh27;
    class UStaticMeshComponent* StaticMesh26;
    class UStaticMeshComponent* StaticMesh25;
    class UStaticMeshComponent* StaticMesh24;
    class UStaticMeshComponent* StaticMesh23;
    class UStaticMeshComponent* StaticMesh22;
    class UStaticMeshComponent* StaticMesh21;
    class UStaticMeshComponent* StaticMesh20;
    class UStaticMeshComponent* StaticMesh19;
    class UStaticMeshComponent* StaticMesh18;
    class UStaticMeshComponent* StaticMesh17;
    class UStaticMeshComponent* StaticMesh16;
    class UStaticMeshComponent* StaticMesh15;
    class UStaticMeshComponent* StaticMesh14;
    class UStaticMeshComponent* StaticMesh13;
    class UStaticMeshComponent* StaticMesh12;
    class UStaticMeshComponent* StaticMesh11;
    class UStaticMeshComponent* StaticMesh10;
    class UStaticMeshComponent* StaticMesh9;
    class UStaticMeshComponent* StaticMesh8;
    class UStaticMeshComponent* StaticMesh7;
    class UStaticMeshComponent* StaticMesh5;
    class UStaticMeshComponent* StaticMesh;
    class UStaticMeshComponent* RelicMapBoard01;
    class UBPRelicAIGarrisonTurret_C* BPRelicAIGarrisonTurret3;
    class UDecalComponent* Decal3;
    class UBPRelicAIGarrisonTurret_C* BPRelicAIGarrisonTurret2;
    class UDecalComponent* Decal2;
    class UBPRelicAIGarrisonTurret_C* BPRelicAIGarrisonTurret1;
    class UDecalComponent* Decal1;
    class UBPRelicAIGarrisonTurret_C* BPRelicAIGarrisonTurret;
    class UDecalComponent* Decal;
    class UStaticMeshComponent* StaticMesh6;
    class UStaticMeshComponent* TurretMesh3;
    class UStaticMeshComponent* TurretMesh1;
    class UStaticMeshComponent* TurretMesh2;
    class UStaticMeshComponent* StaticMesh4;
    class UStaticMeshComponent* TurretMesh;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea2;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea1;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea;
    class UStaticMeshComponent* RoofMesh;
    class UStaticMeshComponent* RelicBaseMesh;

};

#endif
