#ifndef UE4SS_SDK_BPTownBase1_HPP
#define UE4SS_SDK_BPTownBase1_HPP

class ABPTownBase1_C : public ATownBase
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UStaticMeshComponent* FlagMesh;
    class USpawnPointComponent* Spawn9;
    class USpawnPointComponent* Spawn8;
    class USpawnPointComponent* Spawn7;
    class USpawnPointComponent* Spawn6;
    class USpawnPointComponent* Spawn5;
    class USpawnPointComponent* Spawn4;
    class USpawnPointComponent* Spawn3;
    class USpawnPointComponent* Spawn2;
    class USpawnPointComponent* Spawn1;
    class UMultiplexedStaticMeshComponent* MultiplexedRoof;
    class UMultiplexedStaticMeshComponent* MultiplexedBase;
    class UChildActorComponent* OilLantern;
    class UParticleSystemComponent* ParticleSystem;
    class UPointLightComponent* PointLight4;
    class UStaticMeshComponent* StaticMesh16;
    class UPointLightComponent* PointLight3;
    class UStaticMeshComponent* StaticMesh15;
    class UPointLightComponent* PointLight2;
    class UStaticMeshComponent* StaticMesh14;
    class USpotLightComponent* SpotLight1;
    class UStaticMeshComponent* Bollard7;
    class UStaticMeshComponent* Bollard6;
    class UStaticMeshComponent* Bollard5;
    class UStaticMeshComponent* Bollard4;
    class UStaticMeshComponent* Bollard3;
    class UStaticMeshComponent* Bollard2;
    class UStaticMeshComponent* Bollard1;
    class UBoxComponent* Box1;
    class UStaticMeshComponent* IModFileCabinet06;
    class UBoxComponent* Box;
    class UStaticMeshComponent* IModLocker07;
    class UStaticMeshComponent* IModChalkBoard02;
    class UStaticMeshComponent* BottlesCrate02;
    class UStaticMeshComponent* IModDeskPapers01;
    class UStaticMeshComponent* Paper02;
    class UStaticMeshComponent* Paper01;
    class UStaticMeshComponent* IModDeskPapers02;
    class UDecalComponent* Decal36;
    class UDecalComponent* Decal35;
    class UDecalComponent* Decal34;
    class UDecalComponent* Decal33;
    class UDecalComponent* Decal32;
    class UDecalComponent* Decal31;
    class UDecalComponent* Decal30;
    class UDecalComponent* Decal29;
    class UDecalComponent* Decal26;
    class UDecalComponent* Decal27;
    class UDecalComponent* Decal25;
    class UDecalComponent* Decal23;
    class UDecalComponent* Decal24;
    class UDecalComponent* Decal10;
    class UDecalComponent* Decal11;
    class UDecalComponent* Decal22;
    class UDecalComponent* Decal21;
    class UDecalComponent* Decal20;
    class UDecalComponent* Decal19;
    class UDecalComponent* Decal18;
    class UDecalComponent* Decal17;
    class UDecalComponent* Decal28;
    class UDecalComponent* Decal15;
    class UDecalComponent* Decal14;
    class UDecalComponent* Decal13;
    class UDecalComponent* Decal12;
    class UDecalComponent* Decal9;
    class UDecalComponent* Decal8;
    class UDecalComponent* Decal7;
    class UDecalComponent* Decal;
    class UDecalComponent* Decal6;
    class UDecalComponent* Decal16;
    class UStaticMeshComponent* HouseLantern;
    class UStaticMeshComponent* Window5;
    class UStaticMeshComponent* Window4;
    class UStaticMeshComponent* Window3;
    class UStaticMeshComponent* Window2;
    class UStaticMeshComponent* Window1;
    class UStaticMeshComponent* RoofMesh;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea2;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea1;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea;
    class UDecalComponent* Decal5;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_Clock;
    class UDecalComponent* Decal4;
    class UDecalComponent* Decal3;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_Back;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_Right;
    class UDecalComponent* Decal2;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_Left;
    class UDecalComponent* Decal1;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_Front;
    class UCameraComponent* ViewTargetCamera;
    class UStaticMeshComponent* TownBaseMesh;

    void BPSetTeamVisuals(const int32 VisualTeamId);
    void ExecuteUbergraph_BPTownBase1(int32 EntryPoint);
};

#endif
