#ifndef UE4SS_SDK_BPTownBase3_HPP
#define UE4SS_SDK_BPTownBase3_HPP

class ABPTownBase3_C : public ATownBase
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UStaticMeshComponent* FlagMeshRoof;
    class UStaticMeshComponent* FlagMesh;
    class USpawnPointComponent* Spawn19;
    class USpawnPointComponent* Spawn18;
    class USpawnPointComponent* Spawn17;
    class USpawnPointComponent* Spawn16;
    class USpawnPointComponent* Spawn15;
    class USpawnPointComponent* Spawn14;
    class USpawnPointComponent* Spawn13;
    class USpawnPointComponent* Spawn12;
    class USpawnPointComponent* Spawn11;
    class USpawnPointComponent* Spawn10;
    class USpawnPointComponent* Spawn9;
    class USpawnPointComponent* Spawn8;
    class USpawnPointComponent* Spawn7;
    class USpawnPointComponent* Spawn6;
    class USpawnPointComponent* Spawn5;
    class USpawnPointComponent* Spawn4;
    class USpawnPointComponent* Spawn3;
    class USpawnPointComponent* Spawn2;
    class USpawnPointComponent* Spawn1;
    class UMultiplexedStaticMeshComponent* MultiplexedRoof;
    class UMultiplexedStaticMeshComponent* MultiplexedBase;
    class UStaticMeshComponent* Bollard19;
    class UStaticMeshComponent* Bollard18;
    class UStaticMeshComponent* Bollard17;
    class UStaticMeshComponent* Bollard16;
    class UStaticMeshComponent* Bollard15;
    class UStaticMeshComponent* Bollard14;
    class UStaticMeshComponent* Bollard13;
    class UStaticMeshComponent* Bollard12;
    class UStaticMeshComponent* Bollard11;
    class UStaticMeshComponent* Bollard10;
    class UStaticMeshComponent* Bollard9;
    class UStaticMeshComponent* Bollard8;
    class UStaticMeshComponent* Bollard7;
    class UStaticMeshComponent* Bollard6;
    class UStaticMeshComponent* Bollard5;
    class UStaticMeshComponent* Bollard4;
    class UParticleSystemComponent* ParticleSystem1;
    class UParticleSystemComponent* ParticleSystem;
    class USpotLightComponent* SpotLight4;
    class UPointLightComponent* PointLight3;
    class UStaticMeshComponent* StaticMesh15;
    class UPointLightComponent* PointLight2;
    class UStaticMeshComponent* StaticMesh14;
    class USpotLightComponent* SpotLight3;
    class USpotLightComponent* SpotLight2;
    class USpotLightComponent* SpotLight1;
    class UStaticMeshComponent* HouseLantern2;
    class UStaticMeshComponent* HouseLantern1;
    class UStaticMeshComponent* HouseLantern;
    class UDecalComponent* Decal20;
    class UDecalComponent* Decal19;
    class UDecalComponent* Decal18;
    class UDecalComponent* Decal17;
    class UDecalComponent* Decal16;
    class UDecalComponent* Decal15;
    class UDecalComponent* Decal14;
    class UDecalComponent* Decal;
    class UDecalComponent* Decal12;
    class UDecalComponent* Decal11;
    class UDecalComponent* Decal10;
    class UDecalComponent* Decal9;
    class UDecalComponent* Decal8;
    class UDecalComponent* Decal7;
    class UDecalComponent* Decal13;
    class UStaticMeshComponent* Window6;
    class UStaticMeshComponent* Window5;
    class UStaticMeshComponent* Window4;
    class UStaticMeshComponent* Window3;
    class UStaticMeshComponent* Window2;
    class UStaticMeshComponent* Window1;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea3;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea2;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea1;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea;
    class UDecalComponent* Decal6;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_BackRight;
    class UDecalComponent* Decal5;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_FrontRight;
    class UDecalComponent* Decal4;
    class UDecalComponent* Decal3;
    class UDecalComponent* Decal2;
    class UDecalComponent* Decal1;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_BackLeft;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_Right;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_Left;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_FrontLeft;
    class UStaticMeshComponent* RoofMesh;
    class UCameraComponent* ViewTargetCamera;
    class UStaticMeshComponent* TownBaseMesh;

    void BPSetTeamVisuals(const int32 VisualTeamId);
    void ExecuteUbergraph_BPTownBase3(int32 EntryPoint);
};

#endif
