#ifndef UE4SS_SDK_BPTrainCombatCarCLeftGunnerComponent_HPP
#define UE4SS_SDK_BPTrainCombatCarCLeftGunnerComponent_HPP

class UBPTrainCombatCarCLeftGunnerComponent_C : public UBPColVehicleMachineGunnerComponent_C
{
};

#endif
