#ifndef UE4SS_SDK_BPVehicleFactory_HPP
#define UE4SS_SDK_BPVehicleFactory_HPP

class ABPVehicleFactory_C : public AVehicleFactory
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UTemperatureModifierBoxComponent* TemperatureModifierBox;
    class UVisibilityToggleAreaComponent* VisibilityToggleArea;
    class UStaticMeshComponent* Flag;
    class UPointLightComponent* PointLight1;
    class UStaticMeshComponent* Lantern2;
    class UPointLightComponent* PointLight;
    class USpotLightComponent* SpotLight;
    class UStaticMeshComponent* IntLamp2;
    class UStaticMeshComponent* IntLamp1;
    class UStaticMeshComponent* Lantern;
    class UMultiplexedStaticMeshComponent* MultiplexedStaticMesh;
    class UStaticMeshComponent* StaticMesh56;
    class UStaticMeshComponent* StaticMesh55;
    class UStaticMeshComponent* StaticMesh53;
    class UParticleSystemComponent* ParticleSystem6;
    class UBoxComponent* Collision08;
    class UBoxComponent* Collision07;
    class UBoxComponent* Collision06;
    class UBoxComponent* Collision05;
    class UBoxComponent* Collision04;
    class UBoxComponent* Collision03;
    class UBoxComponent* Collision02;
    class UBoxComponent* Collision01;
    class UDecalComponent* Decal16;
    class UDecalComponent* Decal15;
    class UDecalComponent* Decal14;
    class UStaticMeshComponent* StaticMesh52;
    class UStaticMeshComponent* StaticMesh51;
    class UStaticMeshComponent* StaticMesh50;
    class UStaticMeshComponent* StaticMesh49;
    class UStaticMeshComponent* StaticMesh48;
    class UStaticMeshComponent* StaticMesh47;
    class UStaticMeshComponent* StaticMesh46;
    class UStaticMeshComponent* StaticMesh45;
    class UStaticMeshComponent* StaticMesh44;
    class UStaticMeshComponent* StaticMesh43;
    class UStaticMeshComponent* StaticMesh42;
    class UStaticMeshComponent* StaticMesh41;
    class UStaticMeshComponent* StaticMesh40;
    class UStaticMeshComponent* StaticMesh39;
    class UStaticMeshComponent* StaticMesh38;
    class UStaticMeshComponent* StaticMesh37;
    class UParticleSystemComponent* ParticleSystem5;
    class UParticleSystemComponent* ParticleSystem4;
    class UStaticMeshComponent* StaticMesh36;
    class UStaticMeshComponent* StaticMesh35;
    class UParticleSystemComponent* ParticleSystem3;
    class UDecalComponent* Decal13;
    class UStaticMeshComponent* StaticMesh34;
    class UStaticMeshComponent* StaticMesh33;
    class UStaticMeshComponent* StaticMesh32;
    class UStaticMeshComponent* StaticMesh31;
    class UStaticMeshComponent* StaticMesh30;
    class UStaticMeshComponent* StaticMesh29;
    class UStaticMeshComponent* StaticMesh28;
    class UStaticMeshComponent* StaticMesh27;
    class UStaticMeshComponent* SM_Tire_02;
    class UStaticMeshComponent* StaticMesh26;
    class UStaticMeshComponent* SledgeHammer;
    class UStaticMeshComponent* StaticMesh25;
    class UStaticMeshComponent* StaticMesh24;
    class UStaticMeshComponent* StaticMesh23;
    class UStaticMeshComponent* StaticMesh22;
    class UStaticMeshComponent* Toolbox;
    class UParticleSystemComponent* ParticleSystem2;
    class UParticleSystemComponent* ParticleSystem1;
    class UParticleSystemComponent* ParticleSystem;
    class UDecalComponent* Decal12;
    class UDecalComponent* Decal11;
    class UDecalComponent* Decal10;
    class UDecalComponent* Decal9;
    class UDecalComponent* Decal8;
    class UDecalComponent* Decal7;
    class UDecalComponent* Decal6;
    class UDecalComponent* Decal5;
    class UDecalComponent* Decal4;
    class UDecalComponent* Decal3;
    class UDecalComponent* Decal2;
    class UDecalComponent* Decal1;
    class UDecalComponent* Decal;
    class UStaticMeshComponent* StaticMesh21;
    class UStaticMeshComponent* StaticMesh20;
    class UStaticMeshComponent* StaticMesh19;
    class UStaticMeshComponent* StaticMesh18;
    class UStaticMeshComponent* StaticMesh17;
    class UStaticMeshComponent* StaticMesh16;
    class UStaticMeshComponent* StaticMesh15;
    class UStaticMeshComponent* StaticMesh14;
    class UStaticMeshComponent* StaticMesh13;
    class UStaticMeshComponent* StaticMesh12;
    class UStaticMeshComponent* StaticMesh11;
    class UStaticMeshComponent* StaticMesh10;
    class UStaticMeshComponent* StaticMesh9;
    class UStaticMeshComponent* StaticMesh8;
    class UStaticMeshComponent* StaticMesh7;
    class UStaticMeshComponent* StaticMesh6;
    class UStaticMeshComponent* StaticMesh5;
    class UStaticMeshComponent* StaticMesh4;
    class UStaticMeshComponent* StaticMesh3;
    class UStaticMeshComponent* StaticMesh2;
    class UStaticMeshComponent* WoodenCrateTop;
    class UStaticMeshComponent* StaticMesh1;
    class UStaticMeshComponent* StaticMesh;
    class UStaticMeshComponent* FactoryRoof;
    class UStaticMeshComponent* Factory;

    void Deprecated();
    void BPSetTeamVisuals(const int32 VisualTeamId);
    void ExecuteUbergraph_BPVehicleFactory(int32 EntryPoint);
};

#endif
