#ifndef UE4SS_SDK_BPWarVehicleMachineGunnerComponent_HPP
#define UE4SS_SDK_BPWarVehicleMachineGunnerComponent_HPP

class UBPWarVehicleMachineGunnerComponent_C : public UBPColVehicleMachineGunnerComponent_C
{
};

#endif
