#ifndef UE4SS_SDK_BPWoundedCarriedPlayerItemComponent_HPP
#define UE4SS_SDK_BPWoundedCarriedPlayerItemComponent_HPP

class UBPWoundedCarriedPlayerItemComponent_C : public UWoundedCarriedItemComponent
{
};

#endif
