#ifndef UE4SS_SDK_LoreHospital_HPP
#define UE4SS_SDK_LoreHospital_HPP

class ALoreHospital_C : public AActor
{
    class UStaticMeshComponent* StaticMesh71;
    class UStaticMeshComponent* StaticMesh70;
    class UStaticMeshComponent* StaticMesh69;
    class UParticleSystemComponent* Dust;
    class UAudioComponent* Flies_Cue2;
    class UAudioComponent* Flies_Cue;
    class UParticleSystemComponent* Flies2;
    class UParticleSystemComponent* Flies;
    class UStaticMeshComponent* StaticMesh61;
    class UStaticMeshComponent* StaticMesh68;
    class UStaticMeshComponent* StaticMesh67;
    class UStaticMeshComponent* StaticMesh66;
    class UStaticMeshComponent* StaticMesh65;
    class UStaticMeshComponent* StaticMesh64;
    class UStaticMeshComponent* StaticMesh63;
    class UStaticMeshComponent* StaticMesh62;
    class UStaticMeshComponent* StaticMesh60;
    class UStaticMeshComponent* StaticMesh59;
    class UStaticMeshComponent* StaticMesh58;
    class UStaticMeshComponent* StaticMesh57;
    class UStaticMeshComponent* StaticMesh56;
    class UStaticMeshComponent* StaticMesh50;
    class UStaticMeshComponent* StaticMesh54;
    class UStaticMeshComponent* StaticMesh53;
    class UStaticMeshComponent* StaticMesh52;
    class UStaticMeshComponent* StaticMesh51;
    class UStaticMeshComponent* StaticMesh55;
    class UStaticMeshComponent* StaticMesh47;
    class UStaticMeshComponent* StaticMesh44;
    class UStaticMeshComponent* StaticMesh43;
    class UStaticMeshComponent* StaticMesh42;
    class UStaticMeshComponent* StaticMesh34;
    class UStaticMeshComponent* StaticMesh38;
    class UStaticMeshComponent* StaticMesh37;
    class UStaticMeshComponent* StaticMesh36;
    class UStaticMeshComponent* StaticMesh40;
    class UStaticMeshComponent* StaticMesh48;
    class UStaticMeshComponent* StaticMesh45;
    class UStaticMeshComponent* StaticMesh41;
    class UStaticMeshComponent* StaticMesh39;
    class UStaticMeshComponent* StaticMesh33;
    class UStaticMeshComponent* StaticMesh35;
    class UStaticMeshComponent* StaticMesh46;
    class UStaticMeshComponent* StaticMesh49;
    class UStaticMeshComponent* StaticMesh23;
    class UDecalComponent* Decal2;
    class UDecalComponent* Decal1;
    class UDecalComponent* Decal;
    class UStaticMeshComponent* StaticMesh32;
    class UStaticMeshComponent* StaticMesh31;
    class UStaticMeshComponent* StaticMesh30;
    class UStaticMeshComponent* StaticMesh29;
    class UStaticMeshComponent* StaticMesh28;
    class UStaticMeshComponent* StaticMesh27;
    class UStaticMeshComponent* StaticMesh26;
    class UStaticMeshComponent* StaticMesh25;
    class UStaticMeshComponent* StaticMesh24;
    class UStaticMeshComponent* StaticMesh22;
    class UStaticMeshComponent* StaticMesh21;
    class UStaticMeshComponent* StaticMesh20;
    class UStaticMeshComponent* StaticMesh5;
    class UStaticMeshComponent* StaticMesh18;
    class UStaticMeshComponent* StaticMesh17;
    class UStaticMeshComponent* StaticMesh16;
    class UStaticMeshComponent* StaticMesh15;
    class UStaticMeshComponent* StaticMesh14;
    class UStaticMeshComponent* StaticMesh13;
    class UStaticMeshComponent* StaticMesh12;
    class UStaticMeshComponent* Clipboard;
    class UStaticMeshComponent* StaticMesh11;
    class UStaticMeshComponent* StaticMesh;
    class UStaticMeshComponent* StaticMesh10;
    class UStaticMeshComponent* StaticMesh9;
    class UStaticMeshComponent* StaticMesh8;
    class UStaticMeshComponent* StaticMesh7;
    class UStaticMeshComponent* StaticMesh6;
    class UStaticMeshComponent* StaticMesh19;
    class UStaticMeshComponent* StaticMesh1;
    class UStaticMeshComponent* StaticMesh4;
    class UStaticMeshComponent* StaticMesh3;
    class UStaticMeshComponent* StaticMesh2;
    class UBoxComponent* StaticProps;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea;
    class UStaticMeshComponent* Roof;
    class UStaticMeshComponent* TownWMedS1;
    class USceneComponent* DefaultSceneRoot;

};

#endif
