#ifndef UE4SS_SDK_SuperTankWGrenadeLauncherFrontGunnerComponent_HPP
#define UE4SS_SDK_SuperTankWGrenadeLauncherFrontGunnerComponent_HPP

class USuperTankWGrenadeLauncherFrontGunnerComponent_C : public UGrenadeGunnerMountComponent
{
};

#endif
