#ifndef UE4SS_SDK_TownCMedGarrisonG2_HPP
#define UE4SS_SDK_TownCMedGarrisonG2_HPP

class ATownCMedGarrisonG2_C : public AGarrisonHouse
{
    class UStaticMeshComponent* StaticMesh3;
    class UStaticMeshComponent* StaticMesh2;
    class UDecalComponent* Decal46;
    class UDecalComponent* Decal45;
    class UDecalComponent* Decal44;
    class UDecalComponent* Decal43;
    class UDecalComponent* Decal42;
    class UDecalComponent* Decal41;
    class UDecalComponent* Decal40;
    class UDecalComponent* Decal39;
    class UDecalComponent* Decal38;
    class UDecalComponent* Decal37;
    class UDecalComponent* Decal36;
    class UDecalComponent* Decal35;
    class UDecalComponent* Decal34;
    class UDecalComponent* Decal33;
    class UDecalComponent* Decal32;
    class UDecalComponent* Decal31;
    class UStaticMeshComponent* PropagandaPosterColV2;
    class UStaticMeshComponent* PropagandaPosterColV1;
    class UDecalComponent* Decal30;
    class UDecalComponent* Decal29;
    class UDecalComponent* Decal26;
    class UDecalComponent* Decal28;
    class UDecalComponent* Decal27;
    class UDecalComponent* Decal23;
    class UDecalComponent* Decal25;
    class UDecalComponent* Decal24;
    class UDecalComponent* Decal22;
    class UDecalComponent* Decal21;
    class UDecalComponent* Decal20;
    class UDecalComponent* Decal19;
    class UDecalComponent* Decal18;
    class UDecalComponent* Decal17;
    class UDecalComponent* Decal16;
    class UDecalComponent* Decal15;
    class UDecalComponent* Decal14;
    class UDecalComponent* Decal13;
    class UDecalComponent* Decal12;
    class UStaticMeshComponent* StaticMesh1;
    class UStaticMeshComponent* StaticMesh;
    class UStaticMeshComponent* Ivy32;
    class UStaticMeshComponent* Ivy31;
    class UStaticMeshComponent* Ivy30;
    class UStaticMeshComponent* Ivy29;
    class UStaticMeshComponent* Ivy28;
    class UStaticMeshComponent* Ivy27;
    class UStaticMeshComponent* Ivy26;
    class UStaticMeshComponent* Ivy25;
    class UStaticMeshComponent* Ivy24;
    class UStaticMeshComponent* Ivy23;
    class UStaticMeshComponent* Ivy21;
    class UStaticMeshComponent* Ivy20;
    class UStaticMeshComponent* Ivy19;
    class UStaticMeshComponent* Ivy18;
    class UStaticMeshComponent* Ivy17;
    class UStaticMeshComponent* Ivy16;
    class UStaticMeshComponent* Ivy15;
    class UDecalComponent* Decal10;
    class UDecalComponent* Decal9;
    class UDecalComponent* Decal8;
    class UDecalComponent* Decal7;
    class UDecalComponent* Decal6;
    class UDecalComponent* Decal5;
    class UDecalComponent* Decal;
    class UStaticMeshComponent* Window4;
    class UStaticMeshComponent* Window3;
    class UStaticMeshComponent* Window2;
    class UStaticMeshComponent* Window1;
    class UDecalComponent* Decal4;
    class UDecalComponent* Decal3;
    class UDecalComponent* Decal2;
    class UDecalComponent* Decal1;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_Back;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_Right;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_Front;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret_Left;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea1;
    class UMultiplexedStaticMeshComponent* MultiplexedRoof;
    class UMultiplexedStaticMeshComponent* MultiplexedHouse;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea;
    class UStaticMeshComponent* Roof;
    class UStaticMeshComponent* HouseMesh;

};

#endif
