#ifndef UE4SS_SDK_UniqueWWarehouseG2_HPP
#define UE4SS_SDK_UniqueWWarehouseG2_HPP

class AUniqueWWarehouseG2_C : public AGarrisonStation
{
    FPointerToUberGraphFrame UberGraphFrame;
    class USpawnPointComponent* Spawn6;
    class USpawnPointComponent* Spawn5;
    class USpawnPointComponent* Spawn4;
    class USpawnPointComponent* Spawn3;
    class USpawnPointComponent* Spawn2;
    class USpawnPointComponent* Spawn1;
    class USpawnPointComponent* Spawn0;
    class UBoxComponent* ArtilleryShelterWeakPoint;
    class UStaticMeshComponent* window02;
    class UStaticMeshComponent* window01;
    class UStaticMeshComponent* window03;
    class UStaticMeshComponent* window04;
    class UCameraComponent* ViewTargetCamera;
    class UBPBicycleSpawnLocationComponent_C* BPBicycleSpawnLocationComponent;
    class USpotLightComponent* SpotLight3;
    class USpotLightComponent* SpotLight2;
    class USpotLightComponent* SpotLight1;
    class USpotLightComponent* SpotLight;
    class UDecalComponent* AITurretMarker03;
    class UDecalComponent* AITurretMarker02;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret3;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret2;
    class UStaticMeshComponent* RadioStationRoofMesh;
    class UStaticMeshComponent* StaticMesh;
    class UStaticMeshComponent* StaticMesh36;
    class UStaticMeshComponent* StaticMesh1;
    class UStaticMeshComponent* StaticMesh26;
    class UStaticMeshComponent* WoodenCrateTop;
    class UStaticMeshComponent* WoodenCrateBottom02;
    class UBoxComponent* GarrisonStationRadioStationStaticSwap;
    class UStaticMeshComponent* RadioStationMesh;
    class UStaticMeshComponent* WoodenCrateBottom03;
    class UStaticMeshComponent* StaticMesh35;
    class UBoxComponent* GarrisonStationOperatingPostStaticSwap;
    class UStaticMeshComponent* OperatingPostMesh;
    class UStaticMeshComponent* StaticMesh4;
    class UStaticMeshComponent* StaticMesh23;
    class UStaticMeshComponent* StaticMesh6;
    class UStaticMeshComponent* StaticMesh7;
    class UStaticMeshComponent* StaticMesh5;
    class UStaticMeshComponent* StaticMesh25;
    class UStaticMeshComponent* StaticMesh8;
    class UStaticMeshComponent* StaticMesh27;
    class UStaticMeshComponent* StaticMesh3;
    class UStaticMeshComponent* HomeRegionCrates02;
    class UStaticMeshComponent* StaticMesh2;
    class UStaticMeshComponent* StaticMesh28;
    class UBoxComponent* ArtilleryShelterMeshStaticSwap;
    class UStaticMeshComponent* ArtilleryShelterMesh;
    class UStaticMeshComponent* EntranceRampBack;
    class UStaticMeshComponent* EntranceRampFront;
    class UBoxComponent* PillarCollision02;
    class UBoxComponent* PillarCollision01;
    class UStaticMeshComponent* StaticMesh34;
    class UStaticMeshComponent* StaticMesh33;
    class UStaticMeshComponent* StaticMesh32;
    class UStaticMeshComponent* StaticMesh31;
    class UStaticMeshComponent* StaticMesh30;
    class UStaticMeshComponent* StaticMesh29;
    class UDecalComponent* Decal1;
    class UStaticMeshComponent* StaticMesh38;
    class UStaticMeshComponent* StaticMesh37;
    class UStaticMeshComponent* StaticMesh24;
    class UDecalComponent* Decal5;
    class UStaticMeshComponent* HangingWires02;
    class UStaticMeshComponent* StaticMesh22;
    class UStaticMeshComponent* StaticMesh21;
    class UStaticMeshComponent* StaticMesh19;
    class UStaticMeshComponent* StaticMesh18;
    class UStaticMeshComponent* StaticMesh17;
    class UDecalComponent* Decal4;
    class UDecalComponent* Decal3;
    class UStaticMeshComponent* StaticMesh16;
    class UStaticMeshComponent* StaticMesh15;
    class UStaticMeshComponent* StaticMesh14;
    class UStaticMeshComponent* StaticMesh12;
    class UStaticMeshComponent* Shelf01;
    class UStaticMeshComponent* StaticMesh11;
    class UStaticMeshComponent* StaticMesh10;
    class UStaticMeshComponent* StaticMesh9;
    class UDecalComponent* Decal2;
    class UBoxComponent* RailingCollision02;
    class UBoxComponent* RailingCollision01;
    class UDecalComponent* Decal;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea;
    class UMultiplexedStaticMeshComponent* MultiplexedRoof;
    class UStaticMeshComponent* RoofMesh;
    class UDecalComponent* AITurretMarker01;
    class UDecalComponent* AITurretMarker00;
    class UStaticMeshComponent* StaticMesh20;
    class UStaticMeshComponent* StaticMesh13;
    class UBoxComponent* StaticMeshProps;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret1;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret;
    class UMultiplexedStaticMeshComponent* MultiplexedHouse;
    class UStaticMeshComponent* HouseMesh;

    void ReceiveBeginPlay();
    void OnResearched(const class UTechTreeComponent* TechTreeComponent, const ETechComponentID TechID);
    void ExecuteUbergraph_UniqueWWarehouseG2(int32 EntryPoint);
};

#endif
