#ifndef UE4SS_SDK_UniqueWTrainStationG1_HPP
#define UE4SS_SDK_UniqueWTrainStationG1_HPP

class AUniqueWTrainStationG1_C : public AGarrisonHouse
{
    class UBPBicycleSpawnLocationComponent_C* BPBicycleSpawnLocationComponent;
    class UDecalComponent* Decal6;
    class UBoxComponent* PropsCollison03;
    class UStaticMeshComponent* StaticMesh16;
    class UStaticMeshComponent* StaticMesh14;
    class UStaticMeshComponent* StaticMesh45;
    class UStaticMeshComponent* StaticMesh20;
    class UBoxComponent* PropsCollisonMeshes;
    class UStaticMeshComponent* StaticMesh43;
    class UStaticMeshComponent* StaticMesh42;
    class UStaticMeshComponent* PropagandaPosterColV2;
    class UStaticMeshComponent* StaticMesh41;
    class UStaticMeshComponent* PropagandaPosterColV1;
    class UStaticMeshComponent* StaticMesh44;
    class UStaticMeshComponent* StaticMesh39;
    class UStaticMeshComponent* PropagandaPosterWarV9;
    class UStaticMeshComponent* PropagandaPosterWarV5;
    class UStaticMeshComponent* PropagandaPosterWarV4;
    class UStaticMeshComponent* StaticMesh40;
    class UDecalComponent* Decal5;
    class UDecalComponent* Decal4;
    class UDecalComponent* Decal3;
    class UDecalComponent* AITurretMarker00;
    class UBoxComponent* PropsCollison02;
    class UBoxComponent* PropsCollison01;
    class UStaticMeshComponent* StaticMesh2;
    class UStaticMeshComponent* Bench03;
    class UStaticMeshComponent* Bench01;
    class UStaticMeshComponent* Bench02;
    class UDecalComponent* Decal2;
    class UStaticMeshComponent* StaticMesh12;
    class UDecalComponent* Decal;
    class UStaticMeshComponent* StaticMesh1;
    class UStaticMeshComponent* StaticMesh13;
    class UDecalComponent* Decal1;
    class UBoxComponent* StaticMeshProps;
    class UStaticMeshComponent* window02;
    class UStaticMeshComponent* window01;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret1;
    class UBPAIGarrisonTurret_C* BPAIGarrisonTurret;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea1;
    class UBPStructureInteriorArea_C* BPStructureInteriorArea;
    class UStaticMeshComponent* StaticMesh38;
    class UStaticMeshComponent* StaticMesh37;
    class UStaticMeshComponent* StaticMesh36;
    class UStaticMeshComponent* StaticMesh35;
    class UStaticMeshComponent* StaticMesh34;
    class UStaticMeshComponent* StaticMesh33;
    class UStaticMeshComponent* StaticMesh32;
    class UStaticMeshComponent* StaticMesh31;
    class UStaticMeshComponent* StaticMesh30;
    class UStaticMeshComponent* StaticMesh29;
    class UStaticMeshComponent* StaticMesh28;
    class UStaticMeshComponent* StaticMesh27;
    class UStaticMeshComponent* StaticMesh26;
    class UStaticMeshComponent* StaticMesh25;
    class UStaticMeshComponent* StaticMesh24;
    class UStaticMeshComponent* StaticMesh23;
    class UStaticMeshComponent* StaticMesh22;
    class UStaticMeshComponent* StaticMesh5;
    class UStaticMeshComponent* WoodOldPlankSquarev1;
    class UStaticMeshComponent* StaticMesh10;
    class UStaticMeshComponent* StaticMesh9;
    class UStaticMeshComponent* StaticMesh3;
    class UStaticMeshComponent* StaticMesh19;
    class UStaticMeshComponent* StaticMesh18;
    class UStaticMeshComponent* StaticMesh17;
    class UStaticMeshComponent* StaticMesh15;
    class UStaticMeshComponent* StaticMesh11;
    class UStaticMeshComponent* StaticMesh7;
    class UStaticMeshComponent* StaticMesh4;
    class UStaticMeshComponent* StaticMesh;
    class UStaticMeshComponent* StaticMesh8;
    class UStaticMeshComponent* StaticMesh6;
    class UStaticMeshComponent* StaticMesh21;
    class UParticleSystemComponent* ParticleSystem4;
    class UParticleSystemComponent* ParticleSystem1;
    class UMultiplexedStaticMeshComponent* MultiplexedRoof;
    class UMultiplexedStaticMeshComponent* MultiplexedHouse;
    class UStaticMeshComponent* Roof;
    class UStaticMeshComponent* HouseMesh;

};

#endif
